// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLni82ZF_DhdS7LXdqfFK4Z8llg0PfPXQ',
    appId: '1:735539035493:web:ea4c93133bb987b964f58c',
    messagingSenderId: '735539035493',
    projectId: 'bounty-romance',
    authDomain: 'bounty-romance.firebaseapp.com',
    storageBucket: 'bounty-romance.appspot.com',
    measurementId: 'G-LXZE5ELD3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbIfuCnu1qmUHGTDpJKT6VmJCuUYJlb8Y',
    appId: '1:735539035493:android:f643391ab621b7e264f58c',
    messagingSenderId: '735539035493',
    projectId: 'bounty-romance',
    storageBucket: 'bounty-romance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ-s80uzmR_f2tQnVVntCwI4G5RjuDreg',
    appId: '1:735539035493:ios:2e25f45451eeabd564f58c',
    messagingSenderId: '735539035493',
    projectId: 'bounty-romance',
    storageBucket: 'bounty-romance.appspot.com',
    iosBundleId: 'com.example.bountyRomance',
  );
}
